apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-app
  template:
    metadata:
      labels:
        app: hr-app
    spec:
      containers:
        - name: hr-app
          image: srujans29/hr-app:v1.1.1
          ports: 
            - containerPort: 3000
          env:
          - name: MONGODB_URI
            value: "mongodb://mongodb-service:27017/fitness-tracker"
          - name: PORT
            value: "5000"
          - name: HOST
            value: "0.0.0.0"
          - name: NODE_ENV
            value: "production"

---
apiVersion: v1 
kind: Service
metadata: 
  name: hr-app
spec:
  selector:
    app: hr-app
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer

    